base_url = "https://vasylyna.net"
compile_sass = false
build_search_index = false
generate_feed = true
minify_html = false
feed_filename = "rss.xml"

[markdown]
highlight_code = false

[extra]
author = "Volodymyr Vasylyna"
